# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5d40f591e39ec6d92607bded4cf48481098bd7023fc977f025fa6869c3d9c9be0abdd47f204acde553160c4fec529ff12798bd40aab2690caa8f305e0a0acd7

test:
  secret_key_base: 159c1e5d6a9aba4ba3a52420f3abd6a669d277733621bf7d695086812686d06cbcf1ef8206a5ad539c9de034f233fad1fa53535fb0a7561ba217084724e6457f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
